---
- hosts: localhost
  tasks:
    - name: Проверка API Proxmox
      community.general.proxmox:
        api_host: "172.16.10.5"
        api_user: "ansible@pve"
        api_password: "Pharacia_"
        node: "px02"
        vmid: 150
        hostname: "test-container"
        state: present
      register: result

    - debug: var=result
