---
- name: Reboot Windows machine with 10 seconds delay
  hosts: windows
  gather_facts: false

  tasks:
    - name: Wait 10 seconds before reboot
      win_shell: |
        Start-Sleep -Seconds 10

    - name: Reboot the machine
      win_reboot:
        reboot_timeout: 600
        msg: "Перезагрузка через 10 секунд по заданию Ansible"
