---
- name: Create second folder on Windows
  hosts: windows
  gather_facts: false

  tasks:
    - name: Create folder C:\AnsibleDemo6
      win_file:
        path: C:\AnsibleDemo6
        state: directory
