---
- name: Open This PC window on Windows
  hosts: windows
  gather_facts: false

  tasks:
    - name: Open This PC
      win_shell: Start-Process explorer.exe "::{20D04FE0-3AEA-1069-A2D8-08002B30309D}"
