- name: Change scheduled task time to 18:49
  hosts: windows
  gather_facts: false

  tasks:
    - name: Delete old scheduled task if exists
      win_scheduled_task:
        name: OpenThisPC
        state: absent

    - name: Create scheduled task with new time 18:49
      win_scheduled_task:
        name: OpenThisPC
        actions:
          - path: explorer.exe
            arguments: "shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}"
        triggers:
          - type: once
            start_boundary: "{{ lookup('pipe','date -u +%Y-%m-%d') }}T18:49:00"
        username: SYSTEM
        run_level: highest
        state: present
