- name: Выполнить PowerShell скрипт на Windows
  hosts: windows
  gather_facts: false

  tasks:
    - name: Запустить PowerShell скрипт
      win_shell: |
        $folderPath = "C:\Новая папка 6"
        if (-Not (Test-Path $folderPath)) {
          New-Item -Path $folderPath -ItemType Directory
        }
