---
- name: Create second folder on Windows
  hosts: windows
  gather_facts: false

  tasks:
    - name: Create folder C:\AnsibleDemo4
      win_file:
        path: C:\AnsibleDemo4
        state: directory
