- hosts: localhost
  gather_facts: false
  tasks:
    - name: Создать 4 LXC контейнера в Proxmox
      community.general.proxmox:
        api_host: "172.16.10.5"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
        validate_certs: false
        node: "px02"
        vmid: "{{ item.vmid }}"
        hostname: "{{ item.hostname }}"
        ostemplate: "local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst"
        storage: "local-lvm"
        memory: 512
        cores: 1
        swap: 512
        netif: '{"net0":"name=eth0,bridge=vmbr0,ip=dhcp,ip6=auto,type=veth"}'
        password: "Pharacia_"
        state: present
      loop:
        - { vmid: 150, hostname: "container-150" }
        - { vmid: 151, hostname: "container-151" }
        - { vmid: 152, hostname: "container-152" }
        - { vmid: 153, hostname: "container-153" }
