- hosts: localhost
  tasks:
    - name: Создать LXC контейнер в Proxmox с ресурсами
      community.general.proxmox:
        api_host: "172.16.10.5"
        api_user: "ansible@pve"
        api_password: "Pharacia_"
        node: "px02"
        vmid: 150
        hostname: "test-container"
        state: present
        ostemplate: "local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst"
        memory: 2048
        cores: 2
        disk_volume:
          storage: local-lvm
          size: 16G
