---
- name: Создать LXC контейнер в Proxmox с настраиваемыми ресурсами
  hosts: localhost
  gather_facts: false
  vars:
    vmid: 150
    hostname: "test-lxc"
    ostemplate: "local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst"
    storage: "local-lvm"
    disk_size_mb: 16384        # 16 GB = 16*1024 MB
    memory_mb: 2048            # 2 GB RAM
    cores: 2
    net_bridge: "vmbr0"
    net_ip: "192.168.100.50/24"
    net_gateway: "192.168.100.1"

  tasks:
    - name: Создать LXC контейнер с параметрами ресурсов
      community.general.proxmox:
        api_user: "root@pam"
        api_password: "{{ lookup('env', 'PVE_PASS') }}"
        api_host: "172.16.10.5"
        vmid: "{{ vmid }}"
        hostname: "{{ hostname }}"
        ostemplate: "{{ ostemplate }}"
        storage: "{{ storage }}"
        disk_volume:
          size: "{{ disk_size_mb | int }}"
        cores: "{{ cores | int }}"
        memory: "{{ memory_mb | int }}"
        netif:
          net0:
            name: eth0
            bridge: "{{ net_bridge }}"
            ip: "{{ net_ip }}"
            gw: "{{ net_gateway }}"
        state: present
      delegate_to: localhost
