- name: Set system time on Windows to 18:49
  hosts: windows
  gather_facts: false

  tasks:
    - name: Change system time to 18:49
      win_shell: |
        $time = Get-Date
        $newTime = (Get-Date -Year $time.Year -Month $time.Month -Day $time.Day -Hour 18 -Minute 49 -Second 0)
        Set-Date -Date $newTime
