- name: Запуск PowerShell-скрипта на Windows
  hosts: windows
  gather_facts: false

  tasks:
    - name: Создать папку
      win_shell: |
        $folderPath = "C:\Новая папка 47"
        if (-Not (Test-Path $folderPath)) {
          New-Item -Path $folderPath -ItemType Directory
        }

