---
- name: Create Ubuntu 24.04 LXC container on px02
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create LXC
      community.general.proxmox:
        api_host: "172.16.10.5"
        api_user: "ansible@pve"
        api_password: "Pharacia_"
        node: "px02"
        vmid: 150
        hostname: "ubuntu2404-lxc"
        ostemplate: "local:ubuntu-24.04-standard_24.04-2_amd64.tar.zst"
        password: "Pharacia_"
        memory: 1024
        swap: 512
        cores: 2
        netif: '{"net0":"name=eth0,bridge=vmbr0,ip=dhcp"}'
        storage: "local-lvm"
        state: present
