- name: Open This PC via scheduled task at 18:49
  hosts: windows
  gather_facts: false

  tasks:
    - name: Create scheduled task to open This PC at 18:49
      win_shell: |
        schtasks /create /tn "OpenThisPC" /tr "explorer.exe shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}" /sc once /st 18:49 /f /rl highest
