---
- name: Create second folder on Windows
  hosts: windows
  gather_facts: false

  tasks:
    - name: Create folder C:\AnsibleDemo47
      win_file:
        path: C:\AnsibleDemo47
        state: directory
