---
- name: Create LXC container on px02
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create LXC
      community.general.proxmox:
        api_host: "172.16.10.5"
        api_user: "ansible@pve"
        api_password: "Pharacia_"
        node: "px02"
        vmid: 150
        hostname: "test-lxc"
        ostemplate: "local:vztmpl/debian-12-standard_12.0-1_amd64.tar.zst"
        password: "Pharacia_"
        memory: 512
        swap: 512
        cores: 1
        netif: '{"net0":"name=eth0,bridge=vmbr0,ip=dhcp"}'
        storage: "local-lvm"
        state: present
