---
- name: Создать 4 LXC контейнера в Proxmox
  hosts: proxmox
  gather_facts: false
  tasks:
    - name: Создать LXC контейнеры
      community.general.proxmox:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ ansible_user }}"
        api_password: "{{ ansible_password }}"
        # если используешь токены — замени 2 строки выше на:
        # api_token_id: "{{ proxmox_api_token_id }}"
        # api_token_secret: "{{ proxmox_api_token_secret }}"
        validate_certs: "{{ validate_certs | default(False) }}"
        node: "px02"
        vmid: "{{ item.vmid }}"
        hostname: "{{ item.hostname }}"
        ostemplate: "local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst"
        storage: "local-lvm"
        memory: 512
        cores: 1
        swap: 512
        netif: '{"net0":"name=eth0,bridge=vmbr0,ip=dhcp,ip6=auto,type=veth"}'
        state: present
      loop:
        - { vmid: 150, hostname: "container-150" }
        - { vmid: 151, hostname: "container-151" }
        - { vmid: 152, hostname: "container-152" }
        - { vmid: 153, hostname: "container-153" }
