git checkout main
echo -e "collections:\n  - name: community.routeros" > requirements.yml
git add requirements.yml
git commit -m "Add requirements.yml to install community.routeros collection"
git push origin main
